---
deploy:production:
  stage: deploy
  extends:
    - .rules_main_tag
  image: $SERVICE_IMAGE
  script:
    - kubectl config set-cluster k8s --insecure-skip-tls-verify=true --server="$K8S_API_URL"
    - kubectl config set-credentials ci --token="$K8S_CI_TOKEN"
    - kubectl config set-context ci --cluster=k8s --user=ci
    - kubectl config use-context ci
    - |
      echo "IMAGE_TAG: $IMAGE_TAG"
    - helm upgrade --install xpaste .helm
        -f .helm/values.yaml
        -f .helm/values.prod.yaml
        --set image="$CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME"
        --set imageTag="$IMAGE_TAG"
        --debug
        --namespace g000005-xpaste
        --atomic
        --timeout 180s

deploy:dev:
  stage: deploy
  extends:
    - .rules_deploy_dev
    - .environment_prepare
  image: $SERVICE_IMAGE
  script:
    - kubectl config set-cluster k8s --insecure-skip-tls-verify=true --server="$K8S_API_URL"
    - kubectl config set-credentials ci --token="$K8S_CI_TOKEN"
    - kubectl config set-context ci --cluster=k8s --user=ci
    - kubectl config use-context ci
    - |
      echo "IMAGE_TAG: $IMAGE_TAG"
    - helm upgrade --install xpaste .helm
        -f .helm/values.yaml
        -f .helm/values.dev.yaml
        --set image="$CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME"
        --set imageTag="$IMAGE_TAG"
        --set ingress.host="${CI_ENVIRONMENT_SLUG}.${REVIEW_DOMAIN}"
        --debug
        --namespace "$CI_ENVIRONMENT_SLUG"
        --atomic
        --timeout 180s
...
